# Templates for linux, macOS, and Windows
# Based on approach from conda-forge

jobs:
  - template: ./.azure-pipelines/azure-pipelines-syntax.yml
  - template: ./.azure-pipelines/azure-pipelines-linux.yml
    parameters:
      distribution: centos
      version: 6.10
  - template: ./.azure-pipelines/azure-pipelines-osx.yml
    parameters:
      vmImage: macOS-10.14
      xcode_version: 10.2.1
  - template: ./.azure-pipelines/azure-pipelines-win.yml
